site_name: Keyar-mining
docs_dir: sources

site_url: http://synitcool.github.io/keyar-mining
site_author: SynitIsCool
site_description: Package for machine learning and data mining
repo_url: https://github.com/SynitCool/keyar-mining
repo_name: GitHub

copyright: "Keyar-mining is licensed under the <a href='https://github.com/SynitCool/keyar-mining/blob/main/LICENSE'>MIT license</a>"

theme:
  name: material
  palette:
    primary: black

nav:
  - Home: index.md
  - Association Rules:
      - Intro: association_rules/index.md
  - Classification:
      - Intro: classification/index.md
  - Clustering:
      - Intro: clustering/index.md
  - Dataset:
      - Intro: datasets/index.md

plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
